### ISSUE TITLE
sc_12 student type

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#101]
https://github.com/dsu-effectiveness/usheUtils/blob/428ac62838314078ad5b1a4e851a7a4cd3e1c000/R/students_courses.R#L342

After meeting with concurrent enrollment we need to recode this function to something like this:
```r
mutate( sc_student_type = case_when( (str_ends(section_number, "Q") ~ "DC",
              (latest_student_type_code == "H" & budget_code != "BC" & budget_code != "SF")  ~ "EC",
              (latest_student_type_code == "H" & (budget_code == "BC" | budget_code == "SF") & is_concurrent_course) ~ "CC" )) ) %>%
```
I made this change in my branch.

**Comment by CraigDemke** [comment]
@andreabr-dixie if this looks good I will do a pull request.

**Comment by andreabringhurst** [comment]
@cdemkegit , this looks good. Do a pull request.
