### ISSUE TITLE
Add a new line in the mutate statement

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#104]
https://github.com/dsu-effectiveness/usheUtils/blob/8208a8cd01c79be0dd6a610bb470ae8c3ff84cb9/R/courses.R#L396

Added a new campus code:  I01 is new mutate to I (see below)

mutate(c_site_type = case_when( campus_id %in% c("AC1", "AU1", "ACE", "OU1") ~ 'A01',
                                    campus_id == "B8C" ~ 'B80',
                                    campus_id == "UOS" ~ 'C',
                                    str_starts(campus_id, "C") ~ "C",
                                    campus_id == "O03" ~ "O",
                                    campus_id %in% c("O01", "V01") ~ "V",
                                    campus_id == "I01" ~ "I",
                                    TRUE ~ campus_id) ) %>%

**Comment by andreabringhurst** [comment]
@cdemkegit can you get this fixed for @JoyBaule today?

**Comment by CraigDemke** [comment]
I added that line of code.
