### ISSUE TITLE
s_10 in Students adding characters

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#107]
The most recent FIX file for Fall EOT USHE Students Submission is returning an error for element s_10. It is supposed to return just the three digit county code and is now adding UT. For example USHE expects to see s_county_origin as 053, it is now returning UT053.

**Comment by CraigDemke** [comment]
I think I will use the code for the general function and tweak it a little. #
```
gen_ushe_id <- function(input_df=usheUtils::fake_student_df) {
  gen_ushe_id <- NULL

  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( id = if_else(is_valid_ssn(ssn),
                         str_replace_all(ssn, "-", ""),
                         paste0('D', student_id) ) )  %>%

    # Append USHE data element gen_ushe_id
    mutate( gen_ushe_id = id,
            s_03 = id,
            sc_03 = id,
            g_02 = id,
            f_04 = id,
            d_02 = id )

  return(output_df)
}

#' @rdname gen_ushe_id
#' @examples s_03()
#' @export
s_03 <- gen_ushe_id
```

**Comment by CraigDemke** [comment]
https://github.com/dsu-effectiveness/usheUtils/blob/a5f659f727f8c39e720f81042edf9aeaa6760539/R/general.R#L328 

@JoyBaule this will effect g_04 as well as s_10. Do we want to fix it for both or just s_10

**Comment by CraigDemke** [comment]
This is fixed
