### ISSUE TITLE
Change version date to census date for age calculation

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#108]
Please replace version_date with census_date to create correct age calculation for USHE reporting age buckets.

Check to make sure this is changed everywhere, not just in this function.

https://github.com/dsu-effectiveness/usheUtils/blob/a5f659f727f8c39e720f81042edf9aeaa6760539/R/students.R#L785

```
mutate( s_age = floor( as.numeric( (as.Date(census_date) - as.Date(birth_date)) / 365.24 ) ) )

```

**Comment by CraigDemke** [comment]
This has been fixed.
