### ISSUE TITLE
S-44 small fix

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#12]
https://github.com/dsu-effectiveness/usheUtils/blob/de8966b346d733a7cc4af28064072f27601e67c4/R/students.R#L2049 

this needs to be switched so that R comes before E, R is when the aid is received and E is when they are eligible. Everyone who received aid is eligible, but we want the case statement to chose r first.

```r
   mutate(pell_indicator = case_when(
        is_pell_awarded == TRUE ~ "R",
        is_pell_eligible == TRUE ~ "E",
    TRUE ~ ""))
```

**Comment by cyberLaVoy** [comment]
Sounds good. Here is my solution:

```r
    mutate( s_pell = case_when( as.logical(is_pell_awarded) ~ "R",
                                as.logical(is_pell_eligible) ~ "E" ) ) %>%
```

I'm just leaving out the string conversion. I think it's okay if we have NA if is_pell_awarded and is_pell_eligible are both missing.

**Comment by andreabringhurst** [comment]
Looks good.
