### ISSUE TITLE
S-06 S_name

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#14]
S-06 is concatenating Last name, first name, middle name and suffix together, when the function does this, it adds "NA" when missing a suffix or middle name.  

**Example:** 
Montalvo | David | NA | NA  This is not what we would want to submit, instead we would want to submit Montalvo | David | | |

https://github.com/dsu-effectiveness/usheUtils/blob/2f4d50529a51d32905ceaaeb8610eea1bcbd1f69/R/students.R#L521

**Comment by cyberLaVoy** [comment]
Test comment for notification purposes...

**Comment by cyberLaVoy** [comment]
```r
    mutate( s_last = coalesce(last_name, ''),
            s_first = coalesce(first_name, ''),
            s_middle = coalesce(middle_name, ''),
            s_suffix = coalesce(name_suffix, '') ) %>%
```

Wrapping the name character vectors with a coalesce seems to fix this issue.

I plan to follow a similar approach for issues of this nature.

**Comment by andreabringhurst** [comment]
Looks like there are extra spaces around the name.  I'm not sure if they were there before.  They should be removed. Example Walker | Janet | L |

**Comment by cyberLaVoy** [comment]
Will USHE reject our submission if there is white space between pipe delimiters?

**Comment by cyberLaVoy** [comment]
Issue with extra space resolved in package with this:
https://github.com/dsu-effectiveness/usheUtils/blob/c451c8e2595ba51aa455334d39204b4bc6c6bec1/R/students.R#L456

**Comment by andreabringhurst** [comment]
It is now missing the pipes in between the first, last, etc. Looks like AckerGraceJ| should look like Acker|Grace|J|
Previous name looks right.
