### ISSUE TITLE
S-08 Current_zip_code

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#16]
USHE will not allow an international zip code (one that starts with letters) even if it is all we have.  If both local zip and mailing zip are international, we will need to instead submit a null.  Note, we also need to have an error report to try and resolve this, but if it isn't resolved, we need a work around.  Example: 	V1M2B9

```r
s_08 <- function(input_df=usheUtils::fake_student_df, with_intermediates=FALSE) {

  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate(s_curr_zip = coalesce( local_address_zip_code, mailing_address_zip_code ) ) %>%
    # Append USHE data element s_08
    mutate( s_08 = s_curr_zip )

  if (!with_intermediates) {
    output_df <- output_df %>%
      # Remove fields used for intermediate calculations
      select( -c(s_curr_zip) )
  }

  return(output_df)
}
```

**Comment by andreabringhurst** [comment]
What is the difference between blanks and nulls/NA?  I have 3 records that are blank, but 53 that are NA.

**Comment by CraigDemke** [comment]
We can bring in  mailing_address_country_code from export.student_version in Edify. I think the following code or something like it might work:

```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate(s_curr_zip_intermediate = coalesce( local_address_zip_code, mailing_address_zip_code ) ) %>%
    mutate( s_curr_zip = if_else(mailing_address_country_code != "USA", "", s_curr_zip_intermediate )) %>%
    # Append USHE data element s_08
    mutate( s_08 = s_curr_zip )
```

**Comment by andreabringhurst** [comment]
Something isn't working right.  There are now 10489 NA records. Please review.

**Comment by CraigDemke** [comment]
here is what we have in the utvalidate package to check for valid zip codes:

```r
# Regex to check zip code, from:
  # https://regexlib.com/Search.aspx?k=us+zip+code
  zipcode_regex <- "^\\d{5}(-\\d{4})?$"
  matches <- stringr::str_detect(x, zipcode_regex)
  out <- if (missing_ok) {
    matches | is.na(x)
  } else {
    matches & !is.na(x)
  }
  out
}
```

**Comment by cyberLaVoy** [comment]
I think we will want to look at this data field together and discuss a solution.

{utValidateR} should be catching bad zip codes. But we will need to figure out how to make use of this package, in this context.

**Comment by cyberLaVoy** [comment]
We used a different regex expression in this package, than the one use in {utValidateR}. I think we can close this issue, since it is resolved here. But we may want to open an issue on {utValidateR} to update that code with the latest regex expression.

**Comment by andreabringhurst** [comment]
Looks good. No alpha zips.
