### ISSUE TITLE
S-11 s_state_origin

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#17]
I think we have Canadian providences coming in as state codes.  These are not allowed by USHE.  An example is AB or FR.  
The Canadian providences need to be coded as XX.

```r
s_11 <- function(input_df=usheUtils::fake_student_df, with_intermediates=FALSE) {

  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( s_state_origin = first_admit_state_code ) %>%
    # Append USHE data element s_11
    mutate( s_11 = s_state_origin )

  if (!with_intermediates) {
    output_df <- output_df %>%
      # Remove fields used for intermediate calculations
      select( -c(s_state_origin) )
  }

  return(output_df)
}
```

**Comment by andreabringhurst** [comment]
The update is good.  I apologize, I missed saying that NA's should be coded and UN.  Please add that.

**Comment by cyberLaVoy** [comment]
Here is the current solution on master:
https://github.com/dsu-effectiveness/usheUtils/blob/01bce322b7e44d1549e04b12867f101a18d745c0/R/students.R#L753-L757

Proposed solution:
```r
    mutate( s_state_origin = case_when( is.na(first_admit_state_code) ~ "UN",
                                        ( first_admit_country_iso_code != "US"
                                          & !is.na(first_admit_country_iso_code) ) ~ "XX",
                                        TRUE ~ first_admit_state_code ) ) %>%
```

I've included this solution in my latest pull request.

**Comment by cyberLaVoy** [comment]
Solved in the latest merge.

I'm closing the issue for now. But if any more issues come up with this data element, we can reopen this issue.

**Comment by andreabringhurst** [comment]
I think there are more UN's then there should be.  
```
v_s_11a <- student_file_complete %>%
          filter(s_27 != 'US') %>% 
          filter(s_11 != 'XX')
```
I think all of these students should be XX not UN.
