### ISSUE TITLE
running into error when running this function

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#20]
https://github.com/dsu-effectiveness/usheUtils/blob/f2b1d808d77ae0ddcef6d2c8c19bbb9244ec774b/R/courses.R#L473

this is the error I'm getting when trying to run c_08 function:
Error in `mutate()`:
! Problem while computing `c_contact_hrs = if_else(...)`.
Caused by error in `if_else()`:
! `false` must be a double vector, not a character vector.
Backtrace:
   1. ... %>% c_52()
 186. dplyr::if_else(...)

**Comment by cyberLaVoy** [comment]
This issue is solved in latest patch with the following line:

https://github.com/dsu-effectiveness/usheUtils/blob/2f4d50529a51d32905ceaaeb8610eea1bcbd1f69/R/courses.R#L485
