### ISSUE TITLE
C-50 Delivery model: We need to know what ? should be coded as.

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#22]
https://github.com/dsu-effectiveness/usheUtils/blob/2f4d50529a51d32905ceaaeb8610eea1bcbd1f69/R/courses.R#L2119

Andrea, could you write in here what these instruction method codes with ? should be actually be. 

`    mutate(c_delivery_model = case_when( instruction_method_code == "B" ~ 'B',
                                       instruction_method_code == "V" ~ '?', # need to check
                                       instruction_method_code == " " ~ "P", # need to check
                                       instruction_method_code == "E" ~ 'H', # need to check
                                       instruction_method_code == "R" ~ '?', # need to check
                                       instruction_method_code == "I" ~ '?', # need to check
                                       instruction_method_code == "P" ~ '?', # need to check
                                       instruction_method_code == "H" ~ '?', # need to check
                                       instruction_method_code == "O" ~ 'O',
                                       instruction_method_code == "T" ~ 'T',
                                       TRUE ~ instruction_method_code) ) %>%`

**Comment by andreabringhurst** [comment]
Fixed.
