### ISSUE TITLE
student_sql

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#24]
Join to export.academic_programs_version and join program_id to primary_program_id in export.student_term_level_version and pull in ipeds_award_level_code
This will then allow the function for S-19 to change

https://github.com/dsu-effectiveness/ushe_student_file_submission/blob/3986b4aef31a591c43e0fadb24858366ce1341ee/sql/student_file_with_versioning.sql#L37

**Comment by andreabringhurst** [comment]
@jpfeifer-dsu will need to create export.academic_programs_version before this can be done.

**Comment by jpfeifer-dsu** [comment]
Setup export.academic_programs_version and send logic to join to @cdemkegit

**Comment by andreabringhurst** [comment]
This was moved to the master branch.  Looks good.
