### ISSUE TITLE
s-19, s_deg_intent

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#25]
This data element is being maintained in the export.academic_programs_version table.  There is an issue to change student_sql to pull in the right data field (ipeds_award_level_code).  Once this is done, then the R code needs to pull in the data (ipeds_award_level_code), and the mutate statement will only be needed to name the field (like s_18).

https://github.com/dsu-effectiveness/usheUtils/blob/2f4d50529a51d32905ceaaeb8610eea1bcbd1f69/R/students.R#L1076

**Comment by CraigDemke** [comment]
@cyberLaVoy  @andreabr-dixie  academic_programs_version has been added.  I have added ipeds_award_level_code it to the sql file. We need to switch out the function and just pass in  ipeds_award_level_code

**Comment by andreabringhurst** [comment]
NA's should be coded as Zero (0).

**Comment by cyberLaVoy** [comment]
Solved in latest update.

**Comment by andreabringhurst** [comment]
Looks good.
