### ISSUE TITLE
s-22, s_cum_hrs_grad

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#28]
This data looks like it is rounded wrong. It should be numeric and have a decimal one position out (it has no decimal and no characters after a decimal) - 16.5, or 33.3 or 10.0

https://github.com/dsu-effectiveness/usheUtils/blob/2f4d50529a51d32905ceaaeb8610eea1bcbd1f69/R/students.R#L1235

**Comment by andreabringhurst** [comment]
Still missing the decimal.  Should look like S_20.

**Comment by cyberLaVoy** [comment]
Integers should be fine, if we don't have decimal level accuracy on some of our data points. I think we can close this issue, unless USHE complains when we submit.

**Comment by andreabringhurst** [comment]
Let's close and see what happens with USHE.
