### ISSUE TITLE
S-24, s_trans_total

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#30]
Every data record is coming back with 241.14.

https://github.com/dsu-effectiveness/usheUtils/blob/2f4d50529a51d32905ceaaeb8610eea1bcbd1f69/R/students.R#L1330

I documented it wrong.  This should be total transfer hours including clep and ap.  It should have a decimal and one character after the decimal.  I'm not sure what the coding looks like on that.
So, I think this function should be (then get the decimal stuff right as stated in the line above):

```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate(s_trans_total = (transfer_cumulative_credits_earned),
                                 0 ) ) %>%
    # Append USHE data element s_24
    mutate(s_24 = s_trans_total)
```

**Comment by andreabringhurst** [comment]
I need to verify with @jpfeifer-dsu that student_term_level.transfer_cumulative_credits_earned is the data field I need.

**Comment by jpfeifer-dsu** [comment]
Sent logic to Andrea:
SUM(shrtgpa_hours_earned :: NUMERIC) FILTER (
            WHERE
              shrtgpa_gpa_type_ind = 'T'
          ) AS transfer_hours_earned

**Comment by andreabringhurst** [comment]
Thank you @jpfeifer-dsu .  @cyberLaVoy my suggestion is right, we will just need to make sure the decimal is right.

**Comment by andreabringhurst** [comment]
This is still wrong.  All the students have: 241.14 for credits.

**Comment by CraigDemke** [comment]
Removed  total_cumulative_clep_credits_earned, and total_cumulative_ap_credits_earned from  the inputs.

**Comment by cyberLaVoy** [comment]
This should now be resolved in the latest update.

**Comment by andreabringhurst** [comment]
Looks good.
