### ISSUE TITLE
Need to change PF-05 TRUE  to "Y" and FALSE to "N"

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#36]
https://github.com/dsu-effectiveness/usheUtils/blob/e604fdd64c0876d1144355988ca31ecfff1b2b02/R/programs.R#L245

suggested fix:
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( pf_perkins = case_when(
      is_perkins == TRUE ~ "Y",
      TRUE ~ "N")) %>%
    # Append USHE data element pf_06
    mutate( pf_06 = pf_perkins )

  if (!with_intermediates) {
    output_df <- output_df %>%
      # Remove fields used for intermediate calculations
      select( -c(pf_perkins) )
  }
```

**Comment by cyberLaVoy** [comment]
@cdemkegit 
I think this code you submitted for this function solves the issue:
https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/programs.R#L250

Feel free to close the issue, if this looks good on the report end.

**Comment by CraigDemke** [comment]
The function works great.
