### ISSUE TITLE
s_29, House bill 75 Waiver

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#38]
The function is pulling the wrong field.  It should be pulling house_bill_75_waiver.  The SQL is pulling the right field, but the function is not.

https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/students.R#L1528

**Comment by CraigDemke** [comment]
here is my suggestion:

`
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    # TODO: This needs to be implemented.
    mutate( s_hb75_waiver = house_bill_75_waiver ) %>%
    # Append USHE data element s_29
    mutate( s_29 = s_hb75_waiver )
```
`

**Comment by andreabringhurst** [comment]
Looks good.
