### ISSUE TITLE
S_28 High School Code

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#39]
All of the banner fields do not align with USHE.  CHSPE needs to be changed to 459700, 459992 needs to be changed to 459600, 459993 needs to be changed to 459050, 459994 and 459996 needs to be changed to 459200, 459995 needs to be changed to 459300, 459998 needs to be changed to 459500.

https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/students.R#L1491

**Comment by CraigDemke** [comment]
here is what I thought would work:
`
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( s_high_school = case_when(
      latest_high_school_code ==  "CHSPE" ~ "459700",
      latest_high_school_code ==  "459992" ~ "459600",
      latest_high_school_code ==  "459993" ~ "459050",
      latest_high_school_code ==  "459994" ~ "459200",
      latest_high_school_code ==  "459996" ~ "459200",
      latest_high_school_code ==  "459995" ~ "459300",
      latest_high_school_code ==  "459998" ~ "459500",
      TRUE ~ latest_high_school_code)) %>%
    # Append USHE data element s_28
    mutate( s_28 = s_high_school )
```
`

**Comment by andreabringhurst** [comment]
Looks good.
