### ISSUE TITLE
S_32, Total CLEP

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#40]
Should have a decimal and one place after (example 10 should be 10.0).

https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/students.R#L1641

**Comment by CraigDemke** [comment]
here is my suggestion:
`
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( s_total_clep = round(total_cumulative_clep_credits_earned, 3) ) %>%
    # Append USHE data element s_32
    mutate( s_32 = s_total_clep )
```
`

**Comment by andreabringhurst** [comment]
Still missing the decimal.

**Comment by cyberLaVoy** [comment]
This should be solved in the latest update. As before, integers should be fine, unless USHE complains.

**Comment by andreabringhurst** [comment]
Let's close and submit to USHE to see if there are any errors.
