### ISSUE TITLE
S_35, Banner ID

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#42]
Needs to have a D appended to the front of the Banner ID, example D00123456.

https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/students.R#L1751

**Comment by CraigDemke** [comment]
here is my suggestion:


```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( s_banner_id = paste0('D', student_id )) %>%
    # Append USHE data element s_35
    mutate( s_35 = s_banner_id )
```

**Comment by cyberLaVoy** [comment]
That solution will work. Let's include that in the package.
