### ISSUE TITLE
S_42, High school grad date

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#44]
Needs to have the hyphens removed (example 1997-06-01 should be 19970601).

https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/students.R#L2007

**Comment by CraigDemke** [comment]
suggest adding the following:
`@importFrom stringr str_remove_all`

```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( s_hs_grad_date = str_remove_all(high_school_graduation_date, "-")) %>%
    # Append USHE data element s_42
    mutate( s_42 = s_hs_grad_date )
```
I will add this to my branch

**Comment by andreabringhurst** [comment]
looks good.
