### ISSUE TITLE
s_46, major college

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#46]
should pull college_desc

https://github.com/dsu-effectiveness/usheUtils/blob/7b8594b8a1e146033a12d90311485c7a10309be9/R/students.R#L2168

**Comment by andreabringhurst** [comment]
For the most part it looks good.  But S-48, S-49, and S-50 aren't pulling right for 3 people. Let's talk about it.

**Comment by cyberLaVoy** [comment]
@andreabr-dixie Those sound like data integrity issues? And I agree, we should talk about this, before we close the issue.

**Comment by andreabringhurst** [comment]
Looks good.
