### ISSUE TITLE
C_10, Site Type

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#47]
We need to add more to the case statement.  Any that start with a C  needs to be coded as C (like C%); O03 needs to be coded as O.  There is a new code this year - V is taught fully Online; O01 should be coded as V. 

https://github.com/dsu-effectiveness/usheUtils/blob/01bce322b7e44d1549e04b12867f101a18d745c0/R/courses.R#L559

**Comment by andreabringhurst** [comment]
V01 needs to got to V (not A01).  Sorry, I missed that the first time around.

**Comment by CraigDemke** [comment]
I think this will fix it:
```r
 mutate(c_site_type = case_when( campus_id %in% c("AC1", "AU1", "ACE", "OU1") ~ 'A01',
                                    campus_id == "B8C" ~ 'B80',
                                    campus_id == "UOS" ~ 'C',
                                    str_starts(campus_id, "C") ~ "C",
                                    campus_id == "O03" ~ "O",
                                    campus_id %in% c("O01", "V01") ~ "V",
                                    TRUE ~ campus_id) ) %>%
```

**Comment by andreabringhurst** [comment]
Looks good.
