### ISSUE TITLE
C-53, c_site_type2

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#48]
Need to add site_type2, it needs to be tied to building type 2 (c_26).  The SQL is to pull section_schedule.meeting_building_id for the second meeting time.   The R coding is: if not null and building is = to O01 or V01 then V, building is = to HURCTR then B80, else A01.

**Comment by andreabringhurst** [comment]
Should have null's if there is no building 2.  There is a VIRT building, but it is not converting to V.

https://github.com/dsu-effectiveness/usheUtils/blob/c451c8e2595ba51aa455334d39204b4bc6c6bec1/R/courses.R#L2254

**Comment by andreabringhurst** [comment]
There are still no nulls.  It should only be populated when there is a building 2.

Suggested changed to make VIRT and ONLINE populate.
```
 mutate( c_site_type2 = case_when(
      !is.na(meet_building_id_2) &  (meet_building_id_2 == "ONLINE" | meet_building_id_2 == "VIRT") ~ "V",
      meet_building_id_2 == "HURCTR" ~ "B80",
      TRUE ~ "AO1")) %>%
    # Append USHE data element c_53
    mutate( c_53 = c_site_type2 )
```

**Comment by CraigDemke** [comment]
I think this will fix it:
```r
    mutate( c_site_type2 = case_when(
      !is.na(meet_building_id_2) &  (campus_id == "O01" | campus_id == "V01") ~ "V",
      meet_building_id_2 == "HURCTR" ~ "B80",
      !is.na(meet_building_id_2) ~ "AO1",
      TRUE ~ NA_character_)) %>%
```

**Comment by andreabringhurst** [comment]
The nulls is working.  But the VIRT class isn't coming through.
 ```
 mutate( c_site_type2 = case_when(
      !is.na(meet_building_id_2) &  (campus_id == "O01" | campus_id == "V01") ~ "V",
      meet_building_id_2 == "HURCTR" ~ "B80",
      !is.na(meet_building_id_2) ~ "AO1",
      TRUE ~ NA_character_)) %>%
```
Put in this change (change line two from campus_id to meet_building....)
  ```
mutate( c_site_type2 = case_when(
      !is.na(meet_building_id_2) &  (meet_building_id_2 == "ONLINE" | meet_building_id_2 == "VIRT") ~ "V",
      meet_building_id_2 == "HURCTR" ~ "B80",
      !is.na(meet_building_id_2) ~ "AO1",
      TRUE ~ NA_character_)) %>%
```

**Comment by andreabringhurst** [comment]
I still don't think this is working correctly.  I still have one "VIRT" record pulling in an A01 instead of a V.  For this CRN: 	41096
```
v_c_53b <- courses_file_complete %>%
          filter (c_26 == 'VIRT') %>% 
          group_by (c_53, c_26) %>% 
          summarise (count = n_distinct(c_52))

view(v_c_53b)
```

**Comment by andreabringhurst** [comment]
@cdemkegit this still isn't working and it would be good to get it working.  @JoyBaule needs this done today or tomorrow. Please see CRN's 21901 and 21903 for Spring 2023 (202320) 3rd week.

**Comment by CraigDemke** [comment]
I think I fixed it.
