### ISSUE TITLE
C-54, c_site_type3

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#49]
Need to add site_type3, it needs to be tied to building type 3 (c_34).  The SQL is to pull section_schedule.meeting_building_id for the third meeting time.   The R coding is: if not null and building is = to O01 or V01 then V, building is = to HURCTR then B80, else A01.

**Comment by andreabringhurst** [comment]
Should have null's if there is no building 3. There is a VIRT building, but it is not converting to V.

**Comment by andreabringhurst** [comment]
There are still no nulls.  It should only be populated when there is a building 3.

Suggested changed to make VIRT and ONLINE populate.
```
 mutate( c_site_type3 = case_when(
      !is.na(meet_building_id_3) &  (meet_building_id_3 == "ONLINE" | meet_building_id_3 == "VIRT") ~ "V",
      meet_building_id_3 == "HURCTR" ~ "B80",
      TRUE ~ "AO1")) %>%
    # Append USHE data element c_54
    mutate( c_54 = c_site_type3 )

**Comment by CraigDemke** [comment]
I think this will fix it:
```r
 mutate( c_site_type3 = case_when(
      !is.na(meet_building_id_3) &  (campus_id == "O01" | campus_id == "V01") ~ "V",
      meet_building_id_3 == "HURCTR" ~ "B80",
      !is.na(meet_building_id_2) ~ "AO1",
      TRUE ~ NA_character_)) %>%
```

**Comment by andreabringhurst** [comment]
The nulls is working.  But the VIRT class isn't coming through.
 ```
 mutate( c_site_type3 = case_when(
      !is.na(meet_building_id_3) &  (campus_id == "O01" | campus_id == "V01") ~ "V",
      meet_building_id_3 == "HURCTR" ~ "B80",
      !is.na(meet_building_id_3) ~ "AO1",
      TRUE ~ NA_character_)) %>%
```
Put in this change (change line two from campus_id to meet_building....)
  ```
mutate( c_site_type3 = case_when(
      !is.na(meet_building_id_3) &  (meet_building_id_3 == "ONLINE" | meet_building_id_3 == "VIRT") ~ "V",
      meet_building_id_3 == "HURCTR" ~ "B80",
      !is.na(meet_building_id_3) ~ "AO1",
      TRUE ~ NA_character_)) %>%
```

**Comment by andreabringhurst** [comment]
We don't have any courses that in Site Type 3 that should be A01.  But this is using the same code as C_53, and C_53 isn't working right.  Please make the same changes on C_54 that you make to C_53.

**Comment by CraigDemke** [comment]
this was the same issue as c_53. So I either fixed both of them or neither one.
