### ISSUE TITLE
s_03 and sc_03 - SSC needs more shaping to get rid of fake ssns

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#51]
https://github.com/dsu-effectiveness/usheUtils/blob/01bce322b7e44d1549e04b12867f101a18d745c0/R/students.R#L410

Here is what the old sql took care of :
`Here is the code for Invalid SSN's that USHE is using:
INTO #s04b
 FROM students_'+ @extract +'
 WHERE s_instance = @instance
 AND s_inst = @inst
 AND s_id_flag = ''s''
 AND (S_ID IN (''078051120'',''111111111'',''123456789'',''219099999'')
 OR (S_ID >= ''987654320'' AND S_ID <= ''987654329'') 
 OR S_ID=''999999999'' 
 OR S_ID LIKE ''000%'' 
 OR S_ID LIKE ''666%'' 
 OR S_ID LIKE ''9%''
 OR S_ID LIKE ''%[a-Z]%'' 
 OR LEN(S_ID) < 9
 OR SUBSTRING(S_ID,4,2) = ''00''
 OR SUBSTRING(S_ID,6,4) = ''0000'')
 ORDER BY S_ID_error, S_ID`

Here is my suggestion in r to do the same shapping :
 ```r
mutate(f_id = case_when(
  is.na(ssn) ~ paste0('D', student_id),
  str_starts(ssn, "9") == TRUE ~ paste0('D', student_id),
  str_starts(ssn, "666") == TRUE ~ paste0('D', student_id),
  str_ends(ssn, "0000") == TRUE ~ paste0('D', student_id),
  substring(ssn, 4, 5) == "00" ~ paste0('D', student_id),
  string_length(ssn) >= 10,
  ssn == "078051120" | "111111111" | "123456789" | "219099999" ~ paste0('D', student_id),
  str_detect(ssn, [:alpha:]) ~  paste0('D', student_id),
  TRUE ~ str_replace_all(ssn, "-", "") ))
```

**Comment by cyberLaVoy** [comment]
s_03 and sc_03 are the same function.

This issue should be resolved in the latest update.

**Comment by andreabringhurst** [comment]
Looks good. No SSN's starting with 9's.
