### ISSUE TITLE
s_04 - similar fix as s_03 shape fake ssn to student id.

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#52]
https://github.com/dsu-effectiveness/usheUtils/blob/01bce322b7e44d1549e04b12867f101a18d745c0/R/students.R#L459

see #51

**Comment by cyberLaVoy** [comment]
s_03 and sc_03 are the same function.

This issue should be resolved in the latest update.

**Comment by cyberLaVoy** [comment]
Possible solution:
```r
    mutate( s_id_flag = if_else(is.na(ssn) | str_starts(ssn, "9"),
                                'I',
                                'S' ) ) %>%
```

This follows the same logic that we used to get the formatted ssn or student_id in s_03. We will want to make sure the logic vector in the if_else matches for both functions.

**Comment by andreabringhurst** [comment]
No ssn's with leading 9's.  Looks good.

**Comment by andreabringhurst** [comment]
Looks good.
