### ISSUE TITLE
C-39, Start Date

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#54]
Needs to have the hyphens removed from the date (example: 2022-01-04, should be 20220104).

https://github.com/dsu-effectiveness/usheUtils/blob/c9d958a777ecc7b3b442f7abd4388e2bcff5edc3/R/courses.R#L1638

**Comment by CraigDemke** [comment]
made a fix : 
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( c_start_date = str_remove_all(meet_start_date, "-") ) %>%
    # Append USHE data element c_39
    mutate( c_39 = c_start_date )
```

**Comment by andreabringhurst** [comment]
Looks good.
