### ISSUE TITLE
C-40, End Date

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#55]
Needs to have the hyphens removed from the date (Example 2022-01-04, should be 20220104).

https://github.com/dsu-effectiveness/usheUtils/blob/c9d958a777ecc7b3b442f7abd4388e2bcff5edc3/R/courses.R#L1674

**Comment by CraigDemke** [comment]
made a fix:
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( c_end_date =  str_remove_all(meet_end_date, "-") ) %>%
    # Append USHE data element c_40
    mutate( c_40 = c_end_date )
```

**Comment by andreabringhurst** [comment]
Looks good.
