### ISSUE TITLE
C-43, Instructor Name SQL and Function

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#57]
Instructor name should have middle name too.  Currently it has last name, first name.  Change to last name, first name middle name.  Keep the comma between the last name and the first name.  Make sure there is a space between first name and middle name.

https://github.com/dsu-effectiveness/usheUtils/blob/c451c8e2595ba51aa455334d39204b4bc6c6bec1/R/courses.R#L1795

**Comment by CraigDemke** [comment]
The first name and last name needed to be switched also. Here is my fix:
```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( c_instruct_name = paste0(instructor_last_name, ', ', instructor_first_name, ' ', instructor_middle_name) ) %>%
    # Append USHE data element c_43
    mutate( c_43 = c_instruct_name )
```
Primary instructor's name. The legal combination of words by which the  instructor is known. In the format last name, comma, space, first name, space middle name,  comma, space, suffix

**Comment by andreabringhurst** [comment]
Looks good.
