### ISSUE TITLE
s_03 pulling in s_reg_status of CE

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#69]
The output on the file returned by USHE is showing CE/Continuing Ed on some of the s_reg_status, we do not want CE students in this output.

https://github.com/dsu-effectiveness/usheUtils/blob/c247ecc8190029f8491a04fb7cad1db39d4b5c7a/R/students.R#L306

**Comment by andreabringhurst** [comment]
I told Joy the wrong thing.  These should be included in the data pull, but the CE students really should be NM.  I put in a new issue for S-17 to fix this.
