### ISSUE TITLE
sc_07 - Exclude CED students

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#74]
SQL fix to exclude sc_crs_sbj "CED". Fatal error returned on record for Summer EOT: CED 1050 40 and crn 30175.

This error impacts more than one function, do you want me to submit an issue for each one? If the CED issue is fixed in the SQL it will wipe out the other areas where it is returning fatal errors on the ushe FIX file.

https://github.com/dsu-effectiveness/usheUtils/blob/c247ecc8190029f8491a04fb7cad1db39d4b5c7a/R/students_courses.R#L172

**Comment by andreabringhurst** [comment]
Justin fixed this in Edify.
