### ISSUE TITLE
c_11 Exclude CED courses

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#75]
SQL fix request to exclude CED. The fatal error is showing up for CED 1050-40, crn 30175. 

This error is also impacting c_13, please let me know if you want me to submit a separate issue. Once this is fixed though it should wipe out errors that show up in other elements.

https://github.com/dsu-effectiveness/usheUtils/blob/c247ecc8190029f8491a04fb7cad1db39d4b5c7a/R/courses.R#L429

**Comment by CraigDemke** [comment]
@JoyBaule don't worry about more issue if the sql fix will resolve them.

**Comment by andreabringhurst** [comment]
Justin fixed this in Edify.
