### ISSUE TITLE
c_41 Title Special Character

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#76]
USHE documentation does not allow for ampersand or punctuation marks.  Error is on c_title: Community, Public & Global NRS. Possibly change "&" to "and" to avoid errors going forward?

https://github.com/dsu-effectiveness/usheUtils/blob/c247ecc8190029f8491a04fb7cad1db39d4b5c7a/R/courses.R#L1365

**Comment by CraigDemke** [comment]
I think this will work but I want to have someone else look at it:
```r
  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( c_title_intermediate_1 = str_replace_all(course_title, "([,.;-])", "") ) %>%
    mutate( c_title_intermediate_2 = str_replace_all(c_title_intermediate_1, "&", "and") ) %>%
    mutate( c_title = c_title_intermediate_2) %>%
    # Append USHE data element c_41
    mutate( c_41 = c_title )

  return(output_df)
```

**Comment by andreabringhurst** [comment]
Looks good.
