### ISSUE TITLE
s_29 s-hb75_waiver invalid

### ISSUE THREAD

**Issue by JoyLindsay** [dsu-effectiveness/usheUtils#77]
Per USHE fix file, the s_hb75_waiver needs to be less than or equal to 100. Fall FIX files show 146.

https://github.com/dsu-effectiveness/usheUtils/blob/c247ecc8190029f8491a04fb7cad1db39d4b5c7a/R/students.R#L1285

**Comment by andreabringhurst** [comment]
I'm going to reach out to Candi to ask if the 146 is valid.

**Comment by andreabringhurst** [comment]
I checked with Candi and with JD, it is right.  We can move forward.

**Comment by andreabringhurst** [comment]
Looks good.
