### ISSUE TITLE
the period was being removed from data points that need a decimal point.

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#82]
https://github.com/dsu-effectiveness/usheUtils/blob/0a6e4eeb762a8db0fd3982eb4e1ef7cef5f1cf69/R/general.R#L20 
We got our fix file back and there were new issues due to this function.
I removed the period from the list of str_replace items. in my branch;  it will be gone in next pull.
```r
clean <- function(input_df=usheUtils::fake_student_df) {

  # Remove special characters
  input_df[] <- lapply(input_df, function(x) { str_replace_all(x, "[,;:-?]", "") } )
  # Replace & characters with and
  input_df[] <- lapply(input_df,  function(x) { str_replace_all(x, "&", "and") } )

  return(input_df)
}
```

**Comment by cyberLaVoy** [comment]
```r
clean <- function(input_df=usheUtils::fake_student_df) {

  # Remove special characters
  input_df[] <- lapply(input_df, function(x) { if(is.character(x)) { str_replace_all(x, "[.,;:-?]", "") } } )
  # Replace & characters with and
  input_df[] <- lapply(input_df,  function(x) { str_replace_all(x, "&", "and") } )

  return(input_df)
}
```

Here is another possible solution, if you wanted to keep period removal in the function.

**Comment by cyberLaVoy** [comment]
Here is an example I ran to check how is.character would handle different cases.

> is.character(c(1, 2, 3))
[1] FALSE
> is.character(c("a", 2, 3))
[1] TRUE
> is.character(c("a.", 2.2, 3))
[1] TRUE
> c("a.", 2.2, 3)
[1] "a."  "2.2" "3"  
> is.character(c(NA, 2.2, 3))
[1] FALSE
> is.character(c(0, 2.2, 3))
[1] FALSE

**Comment by cyberLaVoy** [comment]
This should be solved from the latest merge.

A confirmation on this fix from a repot end should close the issue.

**Comment by andreabringhurst** [comment]
Looks good.
