### ISSUE TITLE
R_03, Building Number

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#84]
This needs to be a building number not the building abbrv.  I think we need to change the SQL to join to buildings and pull building_number, then the function needs to building_number, not building_id.

Or Justin needs to have building number put in the rooms table.
https://github.com/dsu-effectiveness/usheUtils/blob/1f6f4037325e444743dd393f8559b42e4d7c5a1b/R/rooms.R#L118

**Comment by CraigDemke** [comment]
added building_number from export.buildings in the sqll; I also changed the r code to reflect the data point change:

```r
output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( r_build_number = building_number ) %>%
    # Append USHE data element r_03
    mutate( r_03 =  r_build_number  )
```

**Comment by andreabringhurst** [comment]
Looks good.
