### ISSUE TITLE
B_15, Auxiliary

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#85]
Where building_auxiliary where = Y then A, where N then N.

https://github.com/dsu-effectiveness/usheUtils/blob/1f6f4037325e444743dd393f8559b42e4d7c5a1b/R/buildings.R#L540

**Comment by CraigDemke** [comment]
I think this should take care of the issue:
```r
  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( b_aux = if_else(building_auxiliary == "Y", "A", building_auxiliary) ) %>%
    # Append USHE data element b_15
    mutate( b_15 =  b_aux )
```

**Comment by andreabringhurst** [comment]
Looks good.
