### ISSUE TITLE
This wasn't catching 9's as FALSE

### ISSUE THREAD

**Issue by CraigDemke** [dsu-effectiveness/usheUtils#88]
https://github.com/dsu-effectiveness/usheUtils/blob/7855af3689096fd5c22311838286bfc372c5b25e/R/general.R#L75

Here is the fix I came up with 
```r
is_valid_ssn <- function(ssn) {
  # Note: ssn that start with 9 are actually IRS issued tax IDs; USHE only wants valid ssn.
  ssn_regex <- "^[0-8][0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9]$"

  valid_ssn_check <- str_detect(ssn, ssn_regex)

  valid_ssn_check <- if_else(is.na(valid_ssn_check), FALSE, valid_ssn_check )

  return(valid_ssn_check)
}
```
I just passed the original valid_ssn_check instead of TRUE. Play with it if you want.

**Comment by cyberLaVoy** [comment]
That makes sense. I didn't notice that, when we were looking at it. But this is the logic I had in mind.

**Comment by CraigDemke** [comment]
this is now fixed
