### ISSUE TITLE
C_44, Instruction Type

### ISSUE THREAD

**Issue by andreabringhurst** [dsu-effectiveness/usheUtils#99]
Need to move ENS from LEL to INV.

https://github.com/dsu-effectiveness/usheUtils/blob/8bb37ddceda5763f4689f40fa61e86e24e5002d1/R/courses.R#L1466

Should look like this:
mutate(c_instruct_type = case_when( section_format_type_code %in% c("LEV", "LEX", "LES", "INS")	~	"LEC",
                                        section_format_type_code == "STU"	~	"LEL",
                                        section_format_type_code %in%	c("LBV", "LBS", "LBC")	~	"LAB",
                                        section_format_type_code %in%	c("PRA", "INT", "CLN")	~	"SUP",
                                        section_format_type_code %in% c("MUN", "MUM", "ACT", "ENS")	~	"INV",
                                        section_format_type_code == "CLS"	~	"OTH",
                                        TRUE ~ section_format_type_code)) %>%

**Comment by CraigDemke** [comment]
Made that change.

**Comment by CraigDemke** [comment]
this has been fixed
